include/libswiftnav/ambiguity_test.h
include/libswiftnav/linear_algebra.h
include/libswiftnav/memory_pool.h
include/libswiftnav/printing_utils.h
src/ambiguity_test.c
src/linear_algebra.c
src/memory_pool.c
src/printing_utils.c
tests/check_ambiguity_test.c
tests/check_dgnss_management.c
tests/check_linear_algebra.c
tests/check_memory_pool.c

incomplete: needs better unit tests, remove old ambiguity_sat_inclusion, remove printfs

new ambiguity sat inclusion method

---

clapack-3.2.1-CMAKE/CMakeLists.txt
clapack-3.2.1-CMAKE/F2CLIBS/libf2c/f2c.h
clapack-3.2.1-CMAKE/INCLUDE/f2c.h

Hi,
Here's my second iteration of this patch after Fergus Nobles change requests.
Joe

Minor fixes required for compiling on MinGW-w64.

---

src/ambiguity_test.c
src/dgnss_management.c

Also added some asserts, log_debugs, and documentation for it.
(low latency fixed already had the necessary checks)

Low latency solution checks if the KF has enough sats

---

src/lambda.c
src/linear_algebra.c
tests/check_linear_algebra.c

Remove duplicate UDU/eye/triu functions from lambda.c

---

include/libswiftnav/bits.h
include/libswiftnav/ephemeris.h
src/bits.c
src/ephemeris.c
src/nav_msg.c
tests/check_bits.c

nav_msg.c cleanup

---

include/libswiftnav/amb_kf.h
include/libswiftnav/baseline.h
src/CMakeLists.txt
src/amb_kf.c
src/baseline.c
src/dgnss_management.c
tests/CMakeLists.txt
tests/check_baseline.c
tests/check_main.c
tests/check_suites.h

Refactor and consolidate functions related to calculating baselines from observations and ambiguities and vice versa.
- Rename `stupid_filter.c` -> `baseline.c` (now only contains baseline related functions)
- Move least squares solver out of `amb_kf.c`
- Consolidate the two least squares solvers
- Improve error checking
- Use `DGELSY` instead of `DGELSS` for much better performance whilst retaining decent stability
- Comprehensive unit tests!!
cc: @imh

Refactor baseline calculations

---

include/libswiftnav/nav_msg.h
src/nav_msg.c

Fixes swift-nav/piksi_firmware#305.

Generate histogram for finding nav bit edge.

---

include/libswiftnav/nav_msg.h
src/nav_msg.c

Define constant for invalid TOW return code

---

src/pvt.c

Closes swift-nav/piksi_firmware#339

PVT altitude sanity check: halfway to the moon isn't very sane

---

include/libswiftnav/lambda.h
include/libswiftnav/linear_algebra.h
src/CMakeLists.txt
src/amb_kf.c
src/ambiguity_test.c
src/dgnss_management.c
src/lambda.c
src/linear_algebra.c
src/nav_msg.c
src/printing_utils.c
src/pvt.c
src/sats_management.c
src/single_diff.c
src/tropo.c

Add static qualifiers and remove unused functions / dead code

---

include/libswiftnav/ambiguity_test.h
include/libswiftnav/dgnss_management.h
src/ambiguity_test.c
src/dgnss_management.c

Functions to inspect the probability of an IA vector according to the ambiguity test hypothesis pool.

Functions to inspect the probability of an IA vector according to the ambiguity test hypothesis pool.

---

src/nav_msg.c

Fixes to nav bit synchronization

---

src/track.c

this is a different version of
https://github.com/swift-nav/libswiftnav/pull/136
and believe this version is more correct, because each tot is corrected for satellite bias, before making the selection

use High elevation sat for nominal range

---

include/libswiftnav/track.h
src/track.c

Used for mechanical stress firmware PR: https://github.com/swift-nav/piksi_firmware/pull/418

Improve C/N0 estimator filter.

---

include/libswiftnav/nav_msg.h
include/libswiftnav/track.h
src/nav_msg.c
src/track.c

Work in progress; needs testing; needs updates to libswiftnav-python bindings

Pll retune

---

include/libswiftnav/observation.h
src/observation.c

Supports swift-nav/piksi_firmware#434
@kovach

Add lock counter to single_diff_t, move check_lock_counters into libswiftnav

---

include/libswiftnav/pvt.h
src/pvt.c

DOCS: correct calc_PVT return codes

---

src/pvt.c

PVT: Cheaper HDOP/VDOP

---

src/sats_management.c
tests/CMakeLists.txt
tests/check_ambiguity_test.c
tests/check_main.c
tests/check_sats_management.c
tests/check_suites.h

fix loop error, add unit test

---

include/libswiftnav/almanac.h
src/almanac.c

Signed-off-by: Vlad Ungureanu <vvu@vdev.ro>

Changed almanac functions to take const pointers.

---

DEVELOPMENT.rst
README.md
checks/run-coverage.sh
src/CMakeLists.txt
tests/CMakeLists.txt

improved readme
test target cleans up profiling files
generalized run-coverage

checking stuff

---

checks/checkoutput.sh
checks/pre-commit
docs/CMakeLists.txt
docs/Doxyfile.in
src/CMakeLists.txt

this runs diff between the current branch and master, instead of only looking at staged changes

improve checkoutput script

---

include/libswiftnav/constants.h
include/libswiftnav/ephemeris.h
src/ephemeris.c
tests/check_ephemeris.c

Generalisation of ephemeris for SBAS support.

---

include/libswiftnav/almanac.h
src/almanac.c

Generalisation of almanac for SBAS support.

---

include/libswiftnav/track.h
src/track.c

use arrays of pointers in calc_navigation_measurement()

---

python/swiftnav/pvt.pyx

Previously zeros were returned.
This sort of warning logic should probably be added to other parts of the python/c interface as well.

Issue warnings if calc_PVT fails.

---

include/libswiftnav/constants.h
src/time.c
tests/check_time.c

Also adds test cases for `normalize_gps_time`.

Fix bug in normalize_gps_time

---

include/libswiftnav/time.h
src/ephemeris.c
src/time.c
tests/check_time.c

First step at addressing #265 
Next step will be to make the reference week a firmware setting,.

Add gps_adjust_week_cycle for handling week rollover

---

src/linear_algebra.c
tests/check_linear_algebra.c

Fix bugs in vector_distance

---

tests/CMakeLists.txt
tests/data/l2cbitstream/l2cbitstream_test/main.c
tests/data/l2cbitstream/libl2cbitstream/CMakeLists.txt
tests/data/l2cbitstream/libl2cbitstream/l2cbitstream.c
tests/data/l2cbitstream/libl2cbitstream/l2cbitstream.h
tests/data/l2cbitstream/libl2cbitstream/libl2cbitstreamwrapper.py

C library and Python wrapper. CMake files added.

WIP: Add a library generating L2C message bit stream

---

.gitignore
include/libswiftnav/bits.h
include/libswiftnav/cnav_msg.h
include/libswiftnav/edc.h
libfec/include/libfec/fec.h
libfec/src/viterbi27.c
src/CMakeLists.txt
src/bits.c
src/cnav_msg.c
src/edc.c
tests/CMakeLists.txt
tests/check_bits.c
tests/check_cnav.c
tests/check_main.c
tests/check_suites.h
tests/check_viterbi.c

Added capability to decode GPS CNAV message and extract the following information: CNAV message header, symbol delay.

GPS CNAV message decoding support

---

DEVELOPMENT.md
README.md
python/tests/test_ephemeris.py
src/bits.c
src/ephemeris.c

Also fixes a compile error in `bitshl`

Improve calc_sat_state error checking

---

src/ephemeris.c

Replace | with \ in ephemeris.c doxygen

---

include/libswiftnav/signal.h
src/ephemeris.c
src/nav_msg.c
src/signal.c

This reduces execution time on STM from 15us to 2us.

Remove printf() from sid_to_string()

---

.travis.yml
clapack-3.2.1-CMAKE/F2CLIBS/libf2c/arith_cortex-a9.h
cmake/Toolchain-gcc-arm-embedded.cmake

Processor should be specified e.g.
```
CMAKEFLAGS += -DCMAKE_SYSTEM_PROCESSOR=cortex-a9
```

Add cortex-a9 to toolchain file

---

include/libswiftnav/ephemeris.h

This commit adds definition of Glonass ephemeris data structure.

Add GLO ephemeris

---

include/libswiftnav/constants.h
python/swiftnav/ephemeris.pxd
python/swiftnav/ephemeris.pyx
python/tests/test_ephemeris.py
src/ephemeris.c
tests/check_ephemeris.c

Refer https://github.com/swift-nav/exafore_planning/issues/106 to see dependencies.

WIP: Add GLO orbits computation

---

include/libswiftnav/ephemeris.h
include/libswiftnav/l2c_capability.h
include/libswiftnav/nav_msg.h
python/swiftnav/nav_msg.pxd
python/swiftnav/nav_msg.pyx
src/CMakeLists.txt
src/ephemeris.c
src/l2c_capability.c
src/nav_msg.c
tests/CMakeLists.txt
tests/check_decode_l2c_capability.c
tests/check_main.c
tests/check_suites.h

At the moment discussion is here https://github.com/swift-nav/exafore_planning/issues/38

Add decoding of L2C capability mask

---

include/libswiftnav/observation.h
include/libswiftnav/track.h
python/swiftnav/observation.pxd
python/swiftnav/observation.pyx
python/swiftnav/track.pxd
python/swiftnav/track.pyx
python/tests/test_observation.py
src/baseline.c
src/ephemeris.c
src/observation.c
src/pvt.c
src/rtcm3.c
src/track.c
tests/check_observation.c
tests/check_rtcm3.c

Squashing into two commits to save time and get it ready for @denniszollo to start testing it ASAP.

Final CORS fix PR

---

src/track.c

Updated lock detector algorithm to avoid float to double conversions.

lock_detect: minor fix in lock detector
