- src/ambiguity_test.c
At each point in time, we check to see if an observation plausibly comes from the distribution supposed by each hypothesis. If it does not, then we remove the hypothesis from consideration.
> Single step filter

- include/libswiftnav/nav_msg.h
- src/nav_msg.c
update_nav_msg() takes a parameter for the number of ms accumulated.  This must be 1 until bit sync is established, but may then be increased to 2, 4, 5, 10 or 20.
The update now occurs on the final sample of the bit rather than the first sample of the next bit as it did before.
> Update nav_msg to allow longer tracking integration.

- include/libswiftnav/amb_kf.h
- include/libswiftnav/ambiguity_test.h
- include/libswiftnav/linear_algebra.h
- include/libswiftnav/sats_management.h
- src/amb_kf.c
- src/ambiguity_test.c
- src/linear_algebra.c
- src/sats_management.c
We were thinking that E[code - carrier] == N. We were wrong about the sign on the carrier phase, so now we're using E[code + carrier] == N. It works much better.
With a new accurate Kalman filter, we have trouble when it's state estimates drift away from the hypotheses generated for the ambiguity test. The KF and amb test may disagree. I made the ambiguity test restart when they disagree too much (when they have a null intersection).
I also did some code cleanup, documentation, and made stuff const that should be const.
> Changed the sign on the carrier phase + code observations, and some cleanup

- include/libswiftnav/single_diff.h
- src/ambiguity_test.c
- src/dgnss_management.c
- src/ephemeris.c
- src/single_diff.c
We used to try to add satellites to get up to at least 4 DDs and at most the number the KF is tracking. However, sometimes the KF was tracking less than 5 sats (4 DDs). So counting up from 4 to less than 4 got us into trouble. Now, we properly return "can't add sats."
Also:
- Changed a bunch of functions that should have const arguments so they do now.
- Changed the ephemeris test to also check the healthy flag.
- Resetting the ambiguity test when we are forced to reset the KF.
- Resetting the ambiguity test when we can't rebase the reference satellite.
> No longer trying to add sats when there aren't enough to get 4 DDs minimum

- include/libswiftnav/sbp_utils.h
- src/sbp_utils.c
Currently DOPS messages are sent with garbage TOW values. This adds the ability to set their time.
> BUGFIX: SBP Dops message needs time.

- src/ambiguity_test.c
- src/dgnss_management.c
Switched a log back to old behavior to only print when sdiffs are disordered. This was a log_error where there shouldn't be one.
We have two situations where we can't compute a baseline:
- In one situation, the sats have changed, but we haven't updated the filters yet to take this into account. If the new sat set isn't a superset of the old sat set, we just don't compute a baseline and wait for the filters to update
- In the other situation, we try to use a disordered set of satellites. This shouldn't happen, so when we detect it, we print a log_error.
> Switched a log back to old behavior

- src/linear_algebra.c
Gives marginally better reconstructions of low rank matrices, but more importantly does not fill in any negative elements of D.
> Tweaked UDU to give nonnegative D

- include/libswiftnav/common.h
- include/libswiftnav/nav_msg.h
- src/nav_msg.c
This fixes a lot of 'subframe parity error' messages when the CPU load increases and the nav msg thread is unable to process the subframe in time.  This should also fix the problem of occasionally getting a bad ephemeris.
> Increase the size of nav message subframe bit buffer and check for overrun.

- include/libswiftnav/ambiguity_test.h
- include/libswiftnav/linear_algebra.h
- include/libswiftnav/printing_utils.h
- src/ambiguity_test.c
- src/linear_algebra.c
- src/printing_utils.c
- tests/check_ambiguity_test.c
- tests/check_dgnss_management.c
this should fix an occasional overflow issue in the sat inclusion process. integer ambiguities fit within an s32, but when decorrelated, occasionally exceed that bound.
> S32 -> S64

- include/libswiftnav/ephemeris.h
- include/libswiftnav/single_diff.h
- src/ephemeris.c
- src/single_diff.c
almanacs_to_single_diffs() needs to be elided from libswiftnav-python.  Others aren't referred to anywhere.
> Remove unused functions

- tests/check_coord_system.c
test_random_wgsllh2ecef2llh was sometimes generating LLH coords with negative height
of greater magnitude than the earth's radius at that lat/lon.  We don't proclaim
to handle those cases.
/cc @fnoble @kovach
> Fix occasionally-failing coordinate system unit tests

- include/libswiftnav/dgnss_management.h
As tuned by Ian by looking at SoS innovations from the KF.
This supersedes swift-nav/piksi_firmware#410
Closes #163 
cc: @imh
> Larger initial ambiguity state covariance

- include/libswiftnav/amb_kf.h
- include/libswiftnav/ambiguity_test.h
- src/amb_kf.c
- src/ambiguity_test.c
- src/dgnss_management.c
- tests/check_amb_kf.c
- tests/check_ambiguity_test.c
- tests/check_utils.c
- tests/check_utils.h
Because of cycle slips, false locks, and general mismodelling brought about by changing satellite sets, I opted not to use a data editing scheme, which would have allowed the possibility of locking up the filter forever and worked poorly in testing. Instead, I opted to use a more robust measurement update that essentially allows for heavier tails in the measurement model. If the measurement is good enough, it will be acted upon as normal, and the effect of this change is continuous and smooth. "Good" here refers to an adaptively scaled weighted sum of squares of KF innovations, weighted by their variances.
The KF also now returns whether it thought this data point was an outlier.
- We weight the SOS by their variances instead of by the whole covariance. We saved a few matrix multiplies …
> Added outlier detection and robustness to the KF and amb test

- src/amb_kf.c
- src/ambiguity_test.c
- src/sats_management.c
fixes an issue that may cause memory corruption when the ref satellite changes and the old ref is the largest prn in the sats_management struct
> fixed multiple off by one bugs

- src/nav_msg.c
The TOW validity check is an important bugfix.  We were getting quite a few false preamble/TOW detections.  The subframe bit index check is just for better diagnostics; I have not yet seen it be triggered.
> NAV_MSG: TOW validity check + bound check on subframe bit index

- src/dgnss_management.c
This is a direct log_warn because I didn't want to mess with changing the return codes for the time being.
@kovach
> Fixed baseline raim report

- include/libswiftnav/coord_system.h
- include/libswiftnav/linear_algebra.h
- src/coord_system.c
- src/linear_algebra.c
- src/pvt.c
- tests/check_pvt.c
We were doing two things wrong in our calculations of HDOP and VDOP:
1. Mistakenly squaring the diagonal elements of H_ned before square rooting
2. Rotating only the main diagonal of H to form H_ned.  This isn't legit, because H isn't orthonormal[1].  You have to transform the whole matrix, then look at the diagonal of the result.
This is verified to match SimGEN's idea of all the DOPs to within 1% (remainder probably explained by different original convariance matrices, plus perhaps different representations of NED frame).
cc @fnoble @imh @kovach 
[1] Did I use that linear algebra vocabulary correctly? I mean, the covariance is ellipsoidal, not spherical.
> PVT: Compute HDOP and VDOP correctly

- include/libswiftnav/gpstime.h
- src/ephemeris.c
- src/gpstime.c
- src/track.c
- tests/CMakeLists.txt
- tests/check_gpstime.c
- tests/check_main.c
- tests/check_suites.h
I don't claim that this is the most rigorous possible way of handling time-of-week rollovers, but it's better than keeling over.
In this edition, the tracking channel doesn't attempt to keep track of the week number.  Instead when it's time to form a measurement, it uses gps_time_match_week() to set the measurement week number appropriately from the ephemeris, which may be equal, a week ahead or a week behind.
Bad results are still possible if we happen to have a cached ephemeris that's 7 days out of date and try to use it at just the wrong time.  A separate piksi_firmware update will regularly invalidate outdated ephemerides to prevent that from happening.
@mookerji @fnoble @cbeighley @denniszollo
> Work saturdays

- src/ambiguity_test.c
- src/baseline.c
- src/dgnss_management.c
- src/ephemeris.c
- src/filter_utils.c
- src/lambda.c
- src/nav_msg.c
- src/observation.c
- src/sats_management.c
Used:
```
perl -pi -e 's/(log_.*)\\n"/\1"/' *.c
```
to strip the newlines out of the logging for most cases. Did the rest by hand. Left out the `printf`'s.
/cc @gsmcmullin
> Remove newlines from logs

- checks/run-coverage.sh
- checks/setup-hooks.sh
- include/libswiftnav/ambiguity_test.h
- include/libswiftnav/baseline.h
- include/libswiftnav/memory_pool.h
- include/libswiftnav/observation.h
- include/libswiftnav/printing_utils.h
- include/libswiftnav/sats_management.h
- include/libswiftnav/set.h
- src/ambiguity_test.c
- src/baseline.c
- src/observation.c
- src/printing_utils.c
- src/sats_management.c
- src/set.c
- tests/CMakeLists.txt
- tests/check_baseline.c
- tests/check_dgnss_management.c
- tests/check_set.c
This PR changes baseline_ to compute the intersection between the observation and estimated ambiguity sets, and choose a reference for double differencing based on current SNR.
It also fixes a minor problem with the pre-commit hook.
> Refactor make_dds

- include/libswiftnav/observation.h
- include/libswiftnav/track.h
- src/observation.c
- src/track.c
API changes to 
make_propagated_sdiffs()
calc_navigation_measurement()
check_lock_counters()
all of which now take in ephemeris pointers corresponding to the signals in other arrays instead of the entire global ephemeris array
> remove indexing by PRN

- include/libswiftnav/constants.h
superseded by NUM_SATS in signal.h, but eventually even this should be moved outside of libswiftnav
> delete MAX_SATS define

- CMakeLists.txt
Travis runs ubuntu 12.04 which only has cmake 2.8.7 available.
@mookerji
> Loosen cmake version requirement to 2.8.7 for Travis builds.

- src/nav_msg.c
- src/rtcm3.c
Corrects the printing of SBAS PRNs by using `sid_to_string` in logs.
@jacobmcnamee Can you review?
> Use sid_to_string in logs

- DEVELOPMENT.rst
- include/libswiftnav/constants.h
- include/libswiftnav/ionosphere.h
- src/CMakeLists.txt
- src/almanac.c
- src/ephemeris.c
- src/ionosphere.c
- tests/CMakeLists.txt
- tests/check_ionosphere.c
- tests/check_main.c
- tests/check_suites.h
Implements the ionospheric delay model from GPS ICD.
Next job will be to extract the parameters from the NAV data and apply the corrections for SPP.
Ready for review.
> Add Klobuchar ionoshperic delay model

- python/swiftnav/baseline.pyx
- python/tests/test_baseline.py
When RAIM repair is performed we were returning a residuals array that was too long with junk elements at the end.
cc: @mookerji @ljbade
> Fixes to lesq_solve_raim bindings and tests

- include/libswiftnav/constants.h
- include/libswiftnav/track.h
- src/ephemeris.c
- src/track.c
Continuation of #255. Needed so in https://github.com/swift-nav/piksi_firmware/pull/588 I can exclude unhealthy sats from the solution.
@gsmcmullin Can you review?
> Add alert and healthy flags to solution structs

- README.md
The build status was showing the most recent libswiftnav build (including PRs), so that while looking at the master branch you may see a red "build failed" which actually corresponded to a development branch.
https://github.com/letsencrypt/letsencrypt/issues/927
This change makes it so the build status (on all branches) shows an indicator of the master build.
> Update README.md to show build status for master.

- python/swiftnav/almanac.pyx
- python/tests/test_almanac.py
This changes the almanac initializer to be similar to the ephemeris python binding. The second commit has a failing test with the old initializer and the third commit has a passing test with the new initializer. 
@mookerji @fnoble
> Fix almanac python binding init

- python/swiftnav/dgnss_management.pyx
The call to `make_measurements` was passing the number of sdiffs, not the number of double diffs and the vector passed along was too small (causing seg faults).
@mookerji
> Minor vector length bug in dgnss_management

- tests/CMakeLists.txt
- tests/check_main.c
- tests/check_suites.h
- tests/check_track.c
This was the introduction for Exafore team into unit tests and github work flow.
@swift-nav/firmware @swift-nav/estimation to take a look.
> [TESTS] Add test for costas discriminator.

- python/swiftnav/ambiguity_test.pyx
- python/swiftnav/ephemeris.pyx
- python/swiftnav/observation.pyx
- python/swiftnav/track.pyx
- python/tests/test_observation.py
Notably, adds a test case for the make_propagated_sdiffs function with
some synthetic data taken from Kleeman's SITL runner. The case is
somewhat huge, so I think we'd ultimately want to replace something
like this something that could be generated more cleanly within the
library.
/cc @akleeman @benjamin0 @fnoble
> Print navigation measurements, bug fix, and test.

- python/setup.py
- python/swiftnav/time.pyx
- python/tests/test_time.py
I think this fixes some bugs in the python bindings around gpstime.  I also added a #! to the setup.py
I'm not 100% sure of the intended architecture in the python bindings, but this allowed me to use them.
/cc @mookerji @akleeman 
Next steps are to allow cython to work with a local libswiftnav library.
> Python time bug

- tests/data/l2cbitstream/libl2cbitstream/CMakeLists.txt
Configure CMake to install libl2cbitstream header files
into /usr/local/include/libl2cbitstream/
> Add libl2cbitstream headers installation

- python/swiftnav/dgnss_management.pyx
- src/dgnss_management.c
Use `mk_sdiff_array` in the `dgnss_update` binding.
Also add some `DEBUG` logging for the dgnss functions. Useful for debugging problems with the filter. Based on @akleeman work
@swift-nav/firmware Ready for review.
> Improve dgnss python bindings

- python/tests/test_ephemeris.py
- src/ephemeris.c
Removed need to check `eph->valid` before using `satellite_healthy`
> Check for valid ephemeris in satellite_healthy()

- include/libswiftnav/ephemeris.h
- python/swiftnav/ephemeris.pxd
- python/swiftnav/ephemeris.pyx
- python/tests/test_ephemeris.py
- src/ephemeris.c
The function allows to avoid passing whole ephemeris as parameter.
The change has been done for Nav DB.
> Add ephemeris_params_valid

- src/ephemeris.c
clang on OSX complains about this.  -Werror fails the build.
> One instance of 'abs' should be 'fabs'

- include/libswiftnav/nav_msg_glo.h
- src/nav_msg_glo.c
- tests/check_glo_decoder.c
The commit adds error detection algorithm for GLO nav messages + unit tests.
Requires: https://github.com/swift-nav/libswiftnav/pull/329
> I123 glo decoder error detector

- DEVELOPMENT.md
Mac OS uses `DYLD_LIBRARY_PATH` in place of `LD_LIBRARY_PATH`.
> Add DYLD_LIBRARY_PATH to DEVELOPMENT.md

- include/libswiftnav/track.h
- python/swiftnav/track.pxd
- python/swiftnav/track.pyx
- src/track.c
Compute a receiver time delta for each measurement externally instead of passing in `nav_time` and computing it internally. Avoids subtracting two potentially large doubles to get a small number.
> Pass receiver time delta into calc_navigation_measurement()

- src/dgnss_management.c
Fix passing unitialized `ref_ecef` to `update_ambiguity_test()` due to shadowing:
```
double ref_ecef[3];
{
double ref_ecef[3];
compute_ref_ecef(ref_ecef);
}
use_ref_ecef(ref_ecef);
```
> Fix uninitialized ref_ecef

- include/libswiftnav/ephemeris.h
- include/libswiftnav/ionosphere.h
- include/libswiftnav/nav_msg.h
- python/swiftnav/nav_msg.pxd
- python/swiftnav/nav_msg.pyx
- src/ephemeris.c
- src/ionosphere.c
- src/nav_msg.c
- tests/check_ionosphere.c
This adds decoder for L1C/A iono parameters.
The PR is copy for https://github.com/swift-nav/libswiftnav-private/pull/8
Can be merged.
> Add Iono decoder

- src/ionosphere.c
- tests/check_ionosphere.c
One fabs was missing from the algorithm, caused way too large iono corrections between about 2AM and local dawn.
> Typo in ionosphere.c (gave too large corrections before dawn)
